### ISSUE TITLE
Bug Report Here

### ISSUE THREAD

**Issue by Buizz** [Buizz/EUD-Editor-3#1]
Bug Report Here

**Comment by boermyth** [comment]
I cann't open the EE3 (it will disappear) and my operating system is win 10 64-bit, even though I use the compatibility mode of win xp or 7/8.

**Comment by Buizz** [comment]
The current version is unstable. This can cause unexpected errors. So at least until the Beta version, the detailed bug fixes are difficult.

It should work normally in Windows 10-64bit.

**Comment by Mosby-zhou** [comment]
> I cann't open the EE3 (it will disappear) and my operating system is win 10 64-bit, even though I use the compatibility mode of win xp or 7/8.

me too, win10 will disappear
win7 will open an empty window, and cant close.
