### ISSUE TITLE
EE3-0.13.0.4 SCAFlexble.eps bug

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#100]
The auto-generated `SCAFlexible.eps` has the following compilation error:

![image](https://user-images.githubusercontent.com/37732663/160653439-c4651f75-13d3-483b-985a-d3282858aeb9.png)

Here's auto-generated code of `SCAFlexible.eps`:
![image](https://user-images.githubusercontent.com/37732663/160653756-352e12f5-8369-4484-836b-33d2bdea962c.png)

**Comment by Chromowolf** [comment]
Never mind. Armo has sent a fix

**Comment by Buizz** [comment]
It was fixed in EUD.Editor.3.0.13.0.5.
