### ISSUE TITLE
I open EE3 0.6.0.0 and the window has no icon

### ISSUE THREAD

**Issue by KaguraAkua** [Buizz/EUD-Editor-3#11]
I open  \EUD-Editor-3-master\EUD Editor 3\Data\Downloader and run downloader.exe
it downloads the EE0.6.0.0
after it finished
it open a window without icons
I want to close the window and it display some error text in Korean. 
Would you please tell me how to use EE3?

**Comment by Buizz** [comment]
The latest StarCraft version is not compatible with EUD Editor 2 0.6.0.0v. Versions compatible with the latest StarCraft versions are currently in preparation.

**Comment by CQUTCC** [comment]
Thank you very much.
