### ISSUE TITLE
[ 키인식 루아 오류 + 'N', '.' 키인식 배열 공유 버그

### ISSUE THREAD

**Issue by armoha** [Buizz/EUD-Editor-3#113]
## 주 원인
msqcTool.lua의 KeyParse 함수가 `string.find`를 사용함
```lua
function KeyParse(Key)
    index = string.find("NUMPAD*NUMPAD+NUMPAD-NUMPAD.NUMPAD/*+-./=,`[]\\'", Key)
    if index ~= nii then
        Key = "SP" .. index
    end

    return Key
end
```

## 해결법
- 출처: https://stackoverflow.com/a/18974691

`string.find`의 4번째 인자에 `true`를 넣으면 패턴이 아니라 단순 텍스트로 사용합니다.
```lua
function KeyParse(Key)
    startIndex, endIndex = string.find("NUMPAD*NUMPAD+NUMPAD-NUMPAD.NUMPAD/*+-./=,`[]\\'", Key, 1, true)
    if startIndex ~= nil then
        Key = "SP" .. startIndex .. "_" .. endIndex
    end

    return Key
end
```
(3번째 인자는 원래 기본값이 1임)

## 참고: string.find는 리턴값이 2개입니다 (시작, 끝 범위)

리턴값 1개만 사용하면 시작값만 사용하는거라 `N` 이랑 `NUMPAD*`이 똑같아지는 버그가 있어요:
![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/2a75f604-d896-4051-8e0b-186908880163)

# 1. [ 키인식 루아 오류
## 증상
`<?KeyDown(플레이어, "]")?>` 하면 lua 오류가 납니다: `Malformed pattern (missing ‘]’)`

## 예시
![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/43227a48-b421-42b6-b618-824217c404f8)
![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/b590e039-53a4-4e6a-a61a-86bba5714396)

## 원인
참고: 
- <https://create.roblox.com/docs/luau/strings#string-pattern-reference>
- <https://devforum.roblox.com/t/malformed-pattern-missing/1117490>

Lua의 `string.find` 함수는 **문자열 패턴**을 입력받는 함수입니다. (일종의 정규표현식 비스무리한거...)
총 12개의 문자가 특별한 의미를 갖고 있어요 (이하 '마법 문자'라 칭함):
<html><body>

$ | % | ^ | * | ( | )
-- | -- | -- | -- | -- | --
. | [ | ] | + | - | ?

</body>
</html>

</body>
</html>
(여기서 닫는 괄호들 ) 랑 ] 뺀 10글자들은 현재 오류나거나 예상치 못한 값이 나오는 문제가 생길 수 있어요.)

- `^`와 `$` : 정규표현식처럼 패턴의 시작과 끝을 의미합니다.
- `%` 
  1. `\`처럼 '마법 문자'를 이스케이핑(탈출)할 때 쓰임. `%[` 라고 써야 "["가 됩니다.
  2. `%d` (숫자), `%l` (소문자), `%p` (문장부호) 같이 정규표현식의 `\d`처럼 특정 문자 클래스를 의미함
- `(` 와 `)` : 그룹 캡처
- `[` 와 `]` : 문자 모음
- `*` : 0개 이상
- `+` : 1개 이상
- `-` : 0개 이상의 non-greedy 패턴 (최소로 짧은 패턴에 대응됨)
- `?` : 0개 또는 1개
- `.` : 정규표현식의 `.` 처럼 아무 문자에 대응됨

![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/0ce8aca4-a7f8-4541-8563-9e7dbb1595e4)
![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/3c0d5106-8a8e-4436-a095-7966b1a00a2f)

# 2. 'N', '.' 키인식 배열 공유 버그
## 증상
"N"이랑 "."이 VKeyDown_SP1 으로 중복됩니다. 같은 배열을 사용해요.

## 예시
![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/f6b77197-916a-49fe-a4ec-bc780e00993d)

## 원인
![image](https://github.com/Buizz/EUD-Editor-3/assets/16814706/68eb324d-0aca-4b73-9867-69159dcae1b3)
string.find의 첫 글자가 N이고 . 은 아무 글자에 대응되니까 첫 글자의 시작 끝 범위가 그대로 나옴...

**Comment by Buizz** [comment]
해결
