### ISSUE TITLE
화면 아래에서 자동완성 목록을 띄우면 목록이 아래방향으로 그대로 유지되는 현상이 있습니다

### ISSUE THREAD

**Issue by HeukSulTang** [Buizz/EUD-Editor-3#116]
아래쪽에서 자동완성 목록을 띄우면 자동완성이 아래방향으로 나와서 원하는 요소를 선택하고 싶어도 안 보이는 경우가 가끔 있습니다
화면 아래에서 자동완성을 띄워도 자동완성 목록이 위로 뜰 수 있게 해주실 수 있나요?

이게 화면이 아래에 있을 때, 첫 자동완성이 뜰 때는 위방향으로 잘 떠서 괜찮은데
파일을 연결하여 자동완성이 뜰 경우 아래방향으로 가더라구요

예를 들어
import TETools as te; 임포트하고

.
.
.
.
.
[화면 아래 작업표시줄과 근접한 부분에서]
te 하면 기본 자동목록이 위로 잘 뜸
근데 여기서 TETools 파일 안에 있는 요소들을 사용하기 위해서 점(.)을 찍는 순간 자동완성 목록이 아랫방향으로 갱신됨
te.

사진처럼요!

가끔 키보드 방향키로 아래로 내리면 "가끔씩" 위로 갱신될 때도 있네요

![스크린샷 2024-07-31 004245](https://github.com/user-attachments/assets/c2cd7408-6157-43af-b37b-839bf9344860)

**Comment by Buizz** [comment]
문제 해결했습니다. 다음 버전에 해결됩니다.
![image](https://github.com/user-attachments/assets/9b4df692-6ba2-4fc3-b11f-6cc57ba5422c)

**Comment by Buizz** [comment]
문제 해결했습니다. 다음 버전에 해결됩니다.
![image](https://github.com/user-attachments/assets/a3dffd17-2527-4008-aa3c-22f91eadcb63)
