### ISSUE TITLE
0.18.3.0 - 조건 액션 등 함수 인자가 안 뜹니다

### ISSUE THREAD

**Issue by HeukSulTang** [Buizz/EUD-Editor-3#118]
새 코드에디터에서 fadeIn 같은 거 사용할 때 const tecolor = 0, 4, 0x1F; 이런 식으로 순환할 컬러를 정할 때 배열없이 쉼표로만 해서 작성하잖아요

const a = 0, 1;
const b = 1, 2, 3;
이런 식으로 배열없이 쉼표만 있는 변수를 만들 경우 조건, 액션 등등 함수에 설명 인자들이 안 뜹니다

fadeIn, fadeout 사용할 때는 쉼표로만 작성하는 변수가 거의 반필수인데ㅠㅠ

쉼표버그, 자동완성, 자동완성 선택 등등 이것들만 개선되어도 정말 새 코드에디터 미친듯이 좋을 거 같아요!!

바쁘실 텐데 감사드립니다

![image](https://github.com/user-attachments/assets/4b10835e-035a-46ea-ae7e-3687316f35c2)

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
이 경우 import한 것도 자동완성에 안 뜨네요

**Comment by Buizz** [comment]
![image](https://github.com/user-attachments/assets/cfdbd060-9501-4034-84bf-d7f16b664993)

수정했습니다.

**Comment by HeukSulTang** [comment]
감사합니다!! 혹시 저 상태에서 SetDeaths 같은 조건이나 액션 작성해도 함수 설명이랑 자동완성이 잘 뜨나용?
