### ISSUE TITLE
0.18.3.0 - 자동완성에서 변수 설명이 전부 뜨진 않네요

### ISSUE THREAD

**Issue by HeukSulTang** [Buizz/EUD-Editor-3#119]
다른 건 잘 뜨는데
![image](https://github.com/user-attachments/assets/4651f1f8-bfd3-4a8c-9ea9-aaedac47a997)

배열을
const array = [0,1,2,3,4];
이런 식으로 작성할 경우 

설명이 전부 안 뜨네요

![image](https://github.com/user-attachments/assets/89f64157-53c1-408d-871e-dde4a51a0d97)

**Comment by Buizz** [comment]
;까지 읽게 수정하겠습니다.
현재는 한줄만 읽게 해놔서 그렇습니다.

**Comment by HeukSulTang** [comment]
그렇군요! 
피곤하실 텐데 정말 감사합니당

**Comment by Buizz** [comment]
![image](https://github.com/user-attachments/assets/e49c6765-86c0-457b-b9cc-403d77df28ed)

![image](https://github.com/user-attachments/assets/9b9f13e3-f663-4982-9a3a-6e59f2f9763a)

수정했습니다.
