### ISSUE TITLE
[ ] 로 접는 것에 대해 한 가지 건의드리고 싶은 게 있습니다

### ISSUE THREAD

**Issue by HeukSulTang** [Buizz/EUD-Editor-3#122]
[ ... ] 로 접을 수 있게 패치를 해 주셨잖아요

근데 이게 배열의 인덱스를 정할 때도 

`
const playerEPD = PVariable();

foreach( cp : EUDLoopPlayer()) {
	if(playerEPD[cp] > 0) { 
		내용내용
	}
}
`

이런 식으로 배열[인덱스] 로 사용하잖아요?
이게 접히는 걸로 인식이 돼서 

코드 여러 줄을 접고 싶은데 if문이 접히는 게 아니라 [] 가 접혀서 
![image](https://github.com/user-attachments/assets/a05501c2-f852-49db-a569-886298d0d1e0)

이렇게 됩니다 ㅋ큐

해결이 가능할까용?
혹시 이걸 해결하기 어렵다면
이렇게 되면 [와 ]로 접는 기능을 없애주시는 거 더 좋을 거 같다는 의견을 드리고 싶었습니다

늘 고생이 많으십니다
감사합니다

**Comment by Buizz** [comment]
ㅋㅋㅋㅋ.. 저건 예상 못했네요. 조치하겠습니다.

**Comment by HeukSulTang** [comment]
ㅋㅋ감사합니다! 

아 그리고 혹시 
![image](https://github.com/user-attachments/assets/c26d4c9f-b334-4e9a-93b9-e0bbd8b34cc2)
제가 이렇게 윗줄까지 복사해서 복붙하는 경우가 많은데

이렇게 하면
![image](https://github.com/user-attachments/assets/38b9444d-f544-402d-a483-e79d816f8430)
원래 이렇게 복사가 되었는데


지금은 보니까
![image](https://github.com/user-attachments/assets/e497c93e-4cca-491e-8318-783d6389ed65)
이렇게 복사가 되더라구요!

혹시 이렇게 하신 뜻이 있으실까요?
그게 아니라면 예전처럼 복사가 되도록 가능할까용?

**Comment by HeukSulTang** [comment]
헉 그리고 또 하나 건의 드리고 싶은 게 생겼습니다.

자동완성 선택을 아무것도 입력하지 않으면 안 되도록 하셨던데 의도하신 거죠?
사용하는 게 이것도 괜찮은 거 같은데 유닛이나 로케이션 같이 이름에 규칙이 없고 중구난방인 경우에는 조금 번거롭더라구요?

혹시 아무것도 입력하지 않더라도 엔터, 탭, 마우스 클릭으로는 자동완성 선택이 가능하도록 패치해주실 수 있을까요?

**Comment by Buizz** [comment]
일단 모두 반영했습니다. 근데 자동완성 선택 로직은 원하시는대로 된지 잘 모르겠네요.. 일단 해당 이슈는 닫고 패치 후에도 뭔가 작동이 이상하다면 다시 이슈로 등록해주세요.
