### ISSUE TITLE
@SCABan() 작동 오류

### ISSUE THREAD

**Issue by Tb1281** [Buizz/EUD-Editor-3#123]
function SCABan(BanType)
	preDefine("import TriggerEditor.SCALuaWrapper as scalua;")
	beforeText("scalua.Exec();")
	
	bancode = {
		["OnlyBan"] = 0,
		["BanWithExit"] = 1
	}
	echo("scalua.scaBan(" .. bancode[BanType] .. ")")
end

처럼 "+" 대신 ".."를 써야지 정상 작동됩니다.

**Comment by Buizz** [comment]
수정했습니다.
