### ISSUE TITLE
SCAUseUserMessage가 항상 1임

### ISSUE THREAD

**Issue by Tb1281** [Buizz/EUD-Editor-3#126]
SCATools 의 SCAUseUserMessage 변수가 항상 1입니다.

**Comment by Buizz** [comment]
SCAUseUserMessage를 0으로 대입해도 다시 1이 된다는 의미인가요?

해당 변수는 연결완료, 로드, 저장시 뜨는 메세지가 뜨는지 여부를 나타내는 변수입니다.
건들지 않는다면 기본값은 1입니다.

**Comment by Tb1281** [comment]
항상 1이어서 없애도 되는 변수가 아닌가 해서 여쭤봤습니다.
