### ISSUE TITLE
Render illegal invisible whitespace characters

### ISSUE THREAD

**Issue by armoha** [Buizz/EUD-Editor-3#129]
네이버에서 소스 코드를 복사하면 `​` 같은 투명글자가 같이 복사되서 epScript 문법 오류가 발생하는데, VSCode처럼 투명 글자가 있으면 EUD Editor 상에서 표시해주는 게 오류 찾는 데 도움이 될 거 같습니다.

![image](https://github.com/user-attachments/assets/38247e5c-ccd0-4fcd-8936-50bf72a1bc0b)

**Comment by Buizz** [comment]
![image](https://github.com/user-attachments/assets/5cf26bf8-c827-4242-9a4d-0c6475036731)


패치 완료했습니다. 혹시 다른 특수문자들도 문제가 되는게 있을까요?
