### ISSUE TITLE
Any plans for an Official English release?

### ISSUE THREAD

**Issue by TheOnlyMaldred** [Buizz/EUD-Editor-3#14]
I'd love to help with localization for English!

**Comment by Buizz** [comment]
https://docs.google.com/document/d/1xOEdHd_H4_spJsMZuEGgaxvjrlO9n4H-r5EdTkO_rbc/edit
There is official document for localization.
If you want, you can receive edit permission.

**Comment by TheOnlyMaldred** [comment]
Sent

**Comment by Buizz** [comment]
If you give me a Google mail address, I will allow it.
