### ISSUE TITLE
[Text Bug] The text option in DATA EDITOR is broken

### ISSUE THREAD

**Issue by KanzakiYui** [Buizz/EUD-Editor-3#18]
## Description

I am using latest released version, and no matter how I change in Data Editor/Text option, the actual result in game will lead to everywhere the **_text overflow or is shifted_** (I guess) like a big mess.

## Example

The following is original text
![image](https://user-images.githubusercontent.com/25272408/79058751-dbc31300-7c3f-11ea-82e5-7b48d16175cf.png)

The following is slightly modified text
![image](https://user-images.githubusercontent.com/25272408/79058766-0dd47500-7c40-11ea-9b9a-c7829d52e0e3.png)

The following is what happened in game, as we can see, nearly everywhere text is overflow/shifted
![image](https://user-images.githubusercontent.com/25272408/79058792-5ee46900-7c40-11ea-98c9-0986851f2f30.png)
![image](https://user-images.githubusercontent.com/25272408/79058797-6c99ee80-7c40-11ea-91e4-2006873917d4.png)

## Fact

No matter how I modify any text, seems like all texts will be broken in game, and more what's more interesting is, even when I **_manually revert back_** to original text, the problem still exists. The only one to resolve, is **_right click to Reset_**.
![image](https://user-images.githubusercontent.com/25272408/79058824-aff45d00-7c40-11ea-9e22-eef66b755cc7.png)

## Note

I am using latest version of SC:R

**Comment by Buizz** [comment]
You can change 'datadumper.py' plugin file.
https://drive.google.com/file/d/1Q264b3JZo2fKXpH9tXkrVJo4pO7vC7tI/view?usp=sharing

**Comment by KanzakiYui** [comment]
> You can change 'datadumper.py' plugin file.
> https://drive.google.com/file/d/1Q264b3JZo2fKXpH9tXkrVJo4pO7vC7tI/view?usp=sharing

Tested and it works perfectly so far! Thanks so much for your effort! Will report in the future once encounter such issue again :) 👍
