### ISSUE TITLE
[Bug Feedback] Icons Mismatch

### ISSUE THREAD

**Issue by KanzakiYui** [Buizz/EUD-Editor-3#22]
### Description
There are some icons mismatched in the latest patch, please see below screenshot :)

### Screenshot 
![image](https://user-images.githubusercontent.com/25272408/81626092-b9502100-93c8-11ea-8d9c-91131cf54e9d.png)

**Comment by Buizz** [comment]
That is RIGHT image for Psionic Storm Weapon.

**Comment by KanzakiYui** [comment]
Okay, weird tho... But good to know 👍
