### ISSUE TITLE
[GUI Trigger Editor] Can I know how it works?

### ISSUE THREAD

**Issue by KanzakiYui** [Buizz/EUD-Editor-3#23]
###Description
I knew how epScript works, but today I tried GUI Trigger for curiosity, I found it cannot compile some simple functions(?), maybe I don't have proper setup? 

### Entry Point
![image](https://user-images.githubusercontent.com/25272408/81631716-7eed8080-93d6-11ea-86e8-e531aecbc086.png)

### Main Content
![image](https://user-images.githubusercontent.com/25272408/81631732-8ad94280-93d6-11ea-8ce9-b492ccd30d65.png)

### Compile Result
![image](https://user-images.githubusercontent.com/25272408/81631769-9f1d3f80-93d6-11ea-9b81-80e5ba4e7d94.png)

Please let me know if I need any setup ahead of time :)

**Comment by Buizz** [comment]
![제목 없음](https://user-images.githubusercontent.com/19189816/81643958-ba815c80-9461-11ea-88bc-af92ef1cee36.png)


Please note that TriggerEditor is difficult to use because it has not been properly translated into English.

**Comment by KanzakiYui** [comment]
Tested, and worked! Thanks :)
