### ISSUE TITLE
[BUG] Latest SC:R patch breaks Text Override feature

### ISSUE THREAD

**Issue by KanzakiYui** [Buizz/EUD-Editor-3#25]
### Description

I guess it's due to the latest patch of SC:R today (2020-05-12), thus the text override feature is no longer functional.

### Screenshot
![image](https://user-images.githubusercontent.com/25272408/81773733-fdb9ea80-94b6-11ea-85fc-e04d215597b8.png)

![image](https://user-images.githubusercontent.com/25272408/81773826-3954b480-94b7-11ea-9e65-7966d115075f.png)

### Version
(1) EUD:                 0.9.6.3
(2) euddraft:          0.8.9.9   (with a changed datadumper.py from [here](https://github.com/Buizz/EUD-Editor-3/issues/18#issuecomment-612566896))
(3) SC:R:
![image](https://user-images.githubusercontent.com/25272408/81773956-7caf2300-94b7-11ea-9bdd-7f4f2597b362.png)

**Comment by Buizz** [comment]
업데이트로 인해 모든 tbl 변형 기능이 막혔습니다. 블리자드의 후속 패치를 기다려야 할 거 같습니다.

**Comment by KanzakiYui** [comment]
FYI, today Blizzard released another patch, in this patch, the text are partially fixed (which implies partially broken as well).

Something I noticed is:
(1) rank (terran unit's subtitle) is broken
(2) color of text in unit buttons is broken (only white colour will be shown)

**Comment by Buizz** [comment]
We are already aware of the issue and have requested further updates from Blizzard.
It will probably be fixed in the next patch.

**Comment by armoha** [comment]
This issue has been resolved, Close #25
