### ISSUE TITLE
[Feedback] Minor UI Glitch

### ISSUE THREAD

**Issue by KanzakiYui** [Buizz/EUD-Editor-3#26]
### Screenshot
 
![image](https://user-images.githubusercontent.com/25272408/81889761-6023f100-9572-11ea-8855-7b82e0426459.png)

### Description

Just found a minor UI glitch, **_not a big deal_**, please see above screenshot.

Since the space is limited and not resizable , it cause long texts are truncated. Can we increase the space or make the box container resizable? Thanks! :)

**Comment by Buizz** [comment]
I'm sorry for the delay in solving the problem.
Now in the next version, the size will increase to fit the text.
![image](https://user-images.githubusercontent.com/19189816/99796976-bd2bdf80-2b71-11eb-8ac2-cb0ec18fcbb1.png)
