### ISSUE TITLE
I don't know how to use EE3 without EXE

### ISSUE THREAD

**Issue by boermyth** [Buizz/EUD-Editor-3#3]
I don't know how to use EE3-master without EXE, and when will it be released？Thanks. Unfortunately, I don't know anything about programming.

**Comment by Buizz** [comment]
https://github.com/Buizz/EUD-Editor-3/releases
There is download File

**Comment by boermyth** [comment]
> https://github.com/Buizz/EUD-Editor-3/releases
> There is download File

Thank you so much.
