### ISSUE TITLE
Useful EUD functions from EUD Editor 2?

### ISSUE THREAD

**Issue by milestone-games** [Buizz/EUD-Editor-3#31]
Hi! I'm wondering if the EUD functions that are available in EUD Editor 2 are available in EUD Editor 3?
I'm thinking of being able to use functions like  `SetNextUnitEPD`, `SetCUnitDataEPD` and `SetTech` etc in my eps files.
If they don't exist I was thinking of creating a eps function with these for myself, because it makes it easier to change

`SetCUnitDataEPD(epd, CUnitData.orderID, OrderID.Stop)`  => `bwrite_epd(epd + 0x04D / 4,  0x04D % 4, 1);`

Thanks

**Comment by armoha** [comment]
All TEfunctions are also available in EUD Editor 3.
Trigger editor actions like ` SetNextUnitEPD`, `SetCUnitDataEPD` and `SetTech` are more like macro backed by EE2, which means that epScript function can't get equivalent performance or ease to use.

**Comment by milestone-games** [comment]
Thanks @armoha! Then I will create my own eps file to implement similar functions for my own project for now.

```
function getCommandCard(epd) {
    return wread_epd(epd + 0x094 / 4,  0x094 % 4) ;
}

function setCommandCard(epd, id) {
    wwrite_epd(epd + 0x094 / 4,  0x094 % 4, id);
}
```

**Comment by milestone-games** [comment]
Closing issue since I got my response, feel free to open if you want to continue the discussion :)

**Comment by armoha** [comment]
EE3 has Lua macro `<? ?>`  and you can make your own macro with this.
See: https://github.com/Buizz/EUD-Editor-3/blob/master/EUD%20Editor%203/Data/Lua/TriggerEditor/CUnit.lua
