### ISSUE TITLE
Why can QCUnit appear？

### ISSUE THREAD

**Issue by boermyth** [Buizz/EUD-Editor-3#38]
HI, Buizz

     Glad to write to you, I have a question that I find  QCUnit appears. But it didn't with EE2. What's wrong with me？By the way, how can i upload screenshot here.
     ps: EUD.Editor.3.0.12.4.0 + euddraft 0.9.1.2

**Comment by mighty1231** [comment]
you can directly drag and drop your image from your file browser to this letter box

**Comment by armoha** [comment]
`MSQC` makes unit invisibile once after creating units. Depending on [Plugin] execution order, your DatEdit settings can override building size of QCUnit to make it appear.
