### ISSUE TITLE
The rules of setting password in SCA and EE3 are inconsistent

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#39]
I registered an SCA account, with password having "-" and "@" character. The account was successfully registered, but the password cannot be used in EE3 - SCA settings.
![scap](https://user-images.githubusercontent.com/37732663/111056607-4f5a4980-84bb-11eb-915f-427e9a6e3e14.png)
(I'm sure I've entered the correct battle tag and password. The above picture is just to display the issue). And of course I got compile error:
![QQ图片20210314111141](https://user-images.githubusercontent.com/37732663/111056614-5aad7500-84bb-11eb-9127-04d917779832.png)

euddaft version: 0.9.1.2
EE3 version: 0.12.4.0

I think, either the compiler(or EE3 interpreter?) should support these characters, or SCArchive should not allow these characters appearing in passwords. This inconsistency is a headache for map makers. I'm not sure whether this is EE3's fault or euddraft's fault. Just hope it to be fixed. Could you please help to solve this? thanks

**Comment by Buizz** [comment]
The rules for entering passwords in EUD Editor3 and the rules for entering the actual website are different. The temporary solution is to change the password through the website, and we will make the two input rules the same in the future.

![image](https://user-images.githubusercontent.com/19189816/111151411-c6cecc80-85d2-11eb-998b-a1a1d43a6f9a.png)

![image](https://user-images.githubusercontent.com/19189816/111151494-e0701400-85d2-11eb-9bd8-8547efe6c8fe.png)

**Comment by Chromowolf** [comment]
Thank you very much for your timely response! Already changed my password.
Thanks for your effort in creating SCA, and hope it to be better.

LeeJungHun ***@***.***> 于2021年3月15日周一 下午8:11写道：
