### ISSUE TITLE
Could you add an option for users to select unit name coding?

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#40]
Since euddraft0.9.0.9, a new option is added in order to use utf-8 to decode custom unit name, see:
https://github.com/armoha/euddraft/issues/20#issuecomment-768430406
I need to add 1 line to [main]:
```
[main]
input: input.scx
output: output.scx
decodeUnitName: utf-8
```
But I can't figure out how to add this line in EE3.

**Comment by armoha** [comment]
You can add any option in plugin menu.
You can add new plugin *below* main and write down anything you want.

**Comment by Chromowolf** [comment]
> You can add any option in plugin menu.
> You can add new plugin _below_ main and write down anything you want.

I know I could add new plugin. I just wanna EDIT the [main]. But it cannot be editted:
![image](https://user-images.githubusercontent.com/37732663/111896945-f6a92480-8a57-11eb-92d3-72700a0ea6dc.png)
I tried double click, left click, right click, enter, backspace, etc. None of the ways could I edit it

**Comment by Chromowolf** [comment]
Another GUI problem:
In the plugin menu, when I right click any plugin, and then left click another plugin above, then the 2 plugins would exchange position. I find it weird. Is it an intended feature?

Right-click "ExtraDataEditor":
![image](https://user-images.githubusercontent.com/37732663/111897284-0de91180-8a5a-11eb-9e68-ac016e9533c1.png)

then left-click "DataDumper", then they exchange:
![image](https://user-images.githubusercontent.com/37732663/111897288-15101f80-8a5a-11eb-81d5-40ba8d0235b6.png)

**Comment by Buizz** [comment]
![image](https://user-images.githubusercontent.com/19189816/111949497-2de50780-8b24-11eb-953f-b5fb84b4fb1a.png)

Probably a problem caused by not distinguishing the right and left mouse buttons in implementing the drag function. We will fix it in the next version.

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
