### ISSUE TITLE
SCA code compiling failure: unexpected "scalua.Exec();" line

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#41]
I copied the codes in the following post to NewMain.eps
https://cafe.naver.com/edac/97869
My code:
```js
import TriggerEditor.SCAWrapper as sca;

//Array to store players' mineral amount
const scamin = PVariable(); 

function loadcmp(cp) {
	SetResources(cp, SetTo, scamin[cp], Ore);
	DisplayText("Load complete!");
}

function savecmp(cp) {
	DisplayText("Saved!");
}

function beforeTriggerExec() {
	sca.Exec();
	foreach(cp: EUDLoopPlayer("Human")) {
		setcurpl(cp);
		if (<?ChatEvent("cp", "load")?>) {
			DisplayText("Start loading...");
			sca.scaLoad(0, f_loadcmp);
		}
		
		if (<?ChatEvent("cp", "save")?>) {
			scamin[cp] = <?GetResource("cp", Ore)?>;
			DisplayText("Start saving...");
			sca.scaLoad(0, f_savecmp);
		}
	}
}

```

This is my settings:
![image](https://user-images.githubusercontent.com/37732663/111893936-898a9480-8a41-11eb-9933-ff2c65c674aa.png)

![image](https://user-images.githubusercontent.com/37732663/111893924-737cd400-8a41-11eb-9f57-b636cbb1d946.png)

![image](https://user-images.githubusercontent.com/37732663/111893953-9ad3a100-8a41-11eb-9889-0910bf25fc86.png)

 I got this error:
![image](https://user-images.githubusercontent.com/37732663/111893967-a6bf6300-8a41-11eb-854f-c64591901fbf.png)

So I go to check the build data, I found a new lined add by EE3 in my NewMain.eps
`scalua.Exec();`
in beforeTriggerExec(),
which makes the project fail to compile.
Here is the code generated by EE3 after the compiling:
![image](https://user-images.githubusercontent.com/37732663/111893536-4b3fa600-8a3e-11eb-8296-cf29d8cbf9b7.png)

**Comment by Chromowolf** [comment]
OMG, I delete all the dependency file and reset the MSQC settings and there isn't this bug any more. Weird enough...
This error is hard to reproduce...

**Comment by Buizz** [comment]
`
function beforeTriggerExec() {/*
/*
sca.Exec();
`
If you write this, the code that is automatically added will be commented out.
First of all, let's use it like this and check the fundamental bugs.

**Comment by Chromowolf** [comment]
Thank you. But I can never reproduce this bug again.
I re-do the procedure and  everything goes well. No bugs any more...
(I also corrected the typo `scaLoad` to `scaSave`)

**Comment by armoha** [comment]
How to reproduce: write SCA lua macro without enabling SCA
happened when you got SCA enabled `.e3s` from others.
example: `if (<?SCAWeek("화요일")?>) { }`

How to workaround: I had to write this
```js
function beforeTriggerExec() /*{
	*/{
```
Need to reopen this issue until fixed

**Comment by Chromowolf** [comment]
thank you armo
