### ISSUE TITLE
GUI problem: Font size changes while scrolling

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#42]
I'm trying to scroll the bar to check my code. Sometimes when I scroll my mouse middle button up/down, the font size becomes bigger/smaller at the same time. 
![image](https://user-images.githubusercontent.com/37732663/111893678-57783300-8a3f-11eb-9dc6-0cd0b00d457d.png)
When this happens, I could solve this by holding the "Ctrl" key and scroll my mouse up and down. Then it turns normal (if I scroll my mouse, only the bar moves, the font size keeps unchanged)
This happens randomly, I don't know the cause.

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
