### ISSUE TITLE
[Enhancement] SCA: More global variables? Allow modifying global variables in game?

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#43]
The current SCA only allows players to save/load personnal data, and load global data.
Suppose my map has only 1 variable called "Score". Now I wanna create a live updating leaderboard, storing the top 10 players' game ID and their "Score" values. Also, I wanna load this leaderboard from SCA server and display it in every game.
So, I need more space for the Global Variables. Now we have only 20 global variables, i.e. 80 bytes to manipulate, which is far from enough. Could you add more?
Besides, I also wanna update the leaderboard in game. That is, if some player breaks the record, his score will be automatically uploaded to the server and the leaderboard should be updated automatically as well. However, the global variables cannot be modified in current version of SCA.

I know I could ask the players to go to the SCA website to see the leaderboard by themselves. But it'll be cool to show the leaderboard in game.

Is it possible to add these funtionalities?

**Comment by Buizz** [comment]
I am planning to redesign the SCA system as a whole. This reorganization will incorporate the features you want. But I can't be sure when it will happen.

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
