### ISSUE TITLE
SCAWrapper "bug": Need to call ResetLastMessage() after loading complete

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#44]
I think you also need to reset SCALastMessage to 0 after loading Global Variables and after loading Time:
![image](https://user-images.githubusercontent.com/37732663/113558406-37956180-9632-11eb-8244-00d6a89d8b8e.png)

If you don't call `sca.ResetLastMessage();`, the `SCALastMessage` will remain to be `4` after loading global variables or time variables. If the user then try to `SCAWrapper.scaLoad`, then SCA will be misled and won't load data:
![image](https://user-images.githubusercontent.com/37732663/113558793-dfab2a80-9632-11eb-9421-ea598697b5d3.png)

The map maker must add `sca.ResetLastMessage();` by himself if he wanna load global variable/time.
So IMO, to be consistent and user-friendly, I suggest that add `sca.ResetLastMessage();` in SCAWrapper.eps

**Comment by Buizz** [comment]
I have modified the code.
It will be reflected in the next patch.

**Comment by Chromowolf** [comment]
Thanks for your effort

**Comment by Chromowolf** [comment]
Hi! The newest patch is still using the old SCAWrapper.eps

**Comment by Buizz** [comment]
Okay, I will fixed it
