### ISSUE TITLE
Cannot connect to SCA if "Randomize Start Location" is checked

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#45]
Base map:
![image](https://user-images.githubusercontent.com/37732663/114365099-b0ee0080-9bac-11eb-987a-3aaa826de081.png)

![image](https://user-images.githubusercontent.com/37732663/114365119-b8150e80-9bac-11eb-827a-dcbf497d9350.png)

eps code:
```js
import TriggerEditor.SCArchive as sca;

function onPluginStart() {
	sca.Init();
}

function beforeTriggerExec() {
	//EUDPlayerLoop()();
		//StringBuffer().printfAt(1, "SCAmessage: {}", sca.GetLastMessage());
		//sca.Exec();
	//EUDEndPlayerLoop();
	
	foreach(cp: EUDLoopPlayer("Human")) {
		setcurpl(cp);
		StringBuffer().printfAt(1, "SCAmessage: {}", sca.GetLastMessage());
		sca.Exec();
	}
}

```

In game room:
![image](https://user-images.githubusercontent.com/37732663/114365554-2a85ee80-9bad-11eb-8929-525eae962f8c.png)

In game: 
![image](https://user-images.githubusercontent.com/37732663/114366223-d0395d80-9bad-11eb-8951-9097b345b8c9.png)

As can be seen in the screen shot, I cannot connect to SCA.

But if I uncheck the "Randomize Start Location" in SCMD, then I could connect to SCA normally in game:
![image](https://user-images.githubusercontent.com/37732663/114366683-4047e380-9bae-11eb-9cf6-39abb5eeef4a.png)

![image](https://user-images.githubusercontent.com/37732663/114366648-37571200-9bae-11eb-8ec3-8eba3f0c1d78.png)

To be precise, the sufficient condition for not being able to connect to SCA is:
The player's player index in the game lobby is different from his player index in game. (This won't happen if "Randomized Start Location" is unchecked)

**Comment by armoha** [comment]
EUD Editor 3 should remove all `0x57F1B0` (lobby slot) usages.

https://github.com/Buizz/EUD-Editor-3/blob/b842692a992b3d2678e14bc941dd734b01ffae31/EUD%20Editor%203/Data/TriggerEditor/SCATool.eps#L86-L88
