### ISSUE TITLE
Translating Trigger Editor strings

### ISSUE THREAD

**Issue by milestone-dev** [Buizz/EUD-Editor-3#49]
Hi Buizz!

I want to help translate these strings. Are they in Language/ko-KR.xaml and Language/us-en.xaml?
If not, can you please add so I can translate to English? Thank you!

![Screenshot 2021-06-22 224553](https://user-images.githubusercontent.com/56237952/122996841-9eadf100-d3ab-11eb-86a1-55963d2d2dd1.png)

![Screenshot 2021-06-22 224431](https://user-images.githubusercontent.com/56237952/122996845-9f468780-d3ab-11eb-95c5-3619c924efdf.png)

For Lua groups, I think I can just update the Lua file comments to add English, is that correct? For example in https://github.com/Buizz/EUD-Editor-3/blob/2ff93a7e85f3741e08e30e73d869938713503faa/EUD%20Editor%203/Data/Lua/TriggerEditor/BtnRefresh.lua

![Screenshot 2021-06-22 224506](https://user-images.githubusercontent.com/56237952/122996844-9f468780-d3ab-11eb-81c0-d63838513171.png)

Thanks

**Comment by milestone-dev** [comment]
For LUA functions, can I translate by updating the `@Language.en-US` header in for example https://github.com/Buizz/EUD-Editor-3/blob/2ff93a7e85f3741e08e30e73d869938713503faa/EUD%20Editor%203/Data/Lua/TriggerEditor/BtnRefresh.lua?

**Comment by Buizz** [comment]
You're right about Lua groups.

You can translate it like this.
![image](https://user-images.githubusercontent.com/19189816/123256325-ce840280-d52b-11eb-8b56-f00ae1862302.png)

![image](https://user-images.githubusercontent.com/19189816/123256443-ef4c5800-d52b-11eb-9503-a65f3c6c1ba9.png)


Additional translations of the first will be corrected and uploaded in the next version.

**Comment by milestone-dev** [comment]
@Buizz Thank you so much! I will translate this weekend!

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
