### ISSUE TITLE
Feature request: "link file" in opposite direction

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#51]
The current "link" feature is like:
If a.eps in EE3 is linked (connected) to an external file b.eps, then any modification of a.eps will automatically apply to b.eps.
![image](https://user-images.githubusercontent.com/37732663/124390832-e4f63f00-dd1f-11eb-81bd-79f04a020d05.png)

Could you add a feature that enable file linking in an opposite way? i.e.:
Any modification of the external file will automatically apply to the internal EE3 epscript. I need this feature because sometimes it is more convenient to edit external file than to edit in EE3. I could use any IDE to edit external file.

**Comment by milestone-dev** [comment]
Hi @Chromowolf - this is how I think it works today. I'm using an external text editing program for all my .eps editing. To make sure it does not conflict, I typically close down TE window.

**Comment by Chromowolf** [comment]
> this is how I think it works today.

@milestone-dev  Sorry but I'm not sure what u mean. Did u mean the current EE3 already has the feature that I'm requesting, or?

**Comment by milestone-dev** [comment]
@Chromowolf If I understand you correctly, yes. 

I can currently:
1) Create `Test.eps` file in the same folder as my EE3 project
2) Open Trigger Editor in EE3 and right click -> Import Test.eps
3) Right click Test.eps and select Connect, and select Test.eps in the file manager
4) Close down EE3 Trigger Editor and make changes in of Test.eps in my text editor (e.g Sublime Text)
5) Press Build in EE3, and my updated eps code is compiled

**Comment by Chromowolf** [comment]
@milestone-dev It works. Thanks a lot! So the current "connect" is already a bi-direction one. My fault........
