### ISSUE TITLE
SCA disconnected

### ISSUE THREAD

**Issue by gxz567** [Buizz/EUD-Editor-3#53]
Greetings!
I made a map called "守卫神界" and used SCA, database name is "GDWData001".SCA run nomally till last night.
Since I set the second global data(maybe sth else),SCA becomes hard to connect.It has never happend before.
Today,it is going worse.Either disconnected when first jion game immediately, or disconnected when loading and saving data.

I tried to use backup files of a few days before to use SCA.It successfully load and save data at the first game,but disconnected while the map started at the second game as well.
I'm not sure whether the SCA database is broken or not.
Would you please delete all data completely of account "轻鸿游龙#5217"?Thanks!

**Comment by Buizz** [comment]
I'm not sure what you want.
If the map is still in production, you can create a new map without initializing it by changing the DB ID.
There is no need to delete data.

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
