### ISSUE TITLE
Text entry 1547 (Unlimited) out of range

### ISSUE THREAD

**Issue by milestone-dev** [Buizz/EUD-Editor-3#54]
Steps to reproduce:
- Open EE3
- Click on Data Editor
- Click on Text
- Select entry 1547

![image](https://user-images.githubusercontent.com/56237952/126064070-2b031609-7306-4837-854d-3704d122827a.png)

**Comment by Buizz** [comment]
I solved the problem.
I'll fix it in the next patch.
Thanks for reporting!
