### ISSUE TITLE
Cannot connect to SCA2.0002

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#59]
I entered a SCA-enabled map, and it shows:
![QQ图片20210817014033](https://user-images.githubusercontent.com/37732663/129611009-5b3cbd96-f073-4b08-938d-4a34cdc54124.png)

How to solve this?

**Comment by Buizz** [comment]
It is solved by building with 0.12.7.0 version.
0.12.7.0 will be uploaded soon.

**Comment by Chromowolf** [comment]
thx
