### ISSUE TITLE
SCA bug: Exit game while uploading leads to erasing pernal data

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#60]
If I exit game while SCA is uploading data (before SCA finishes uploading), then all my personal data will be erased (all my SCA variables become 0). 
Based on testing, it seems that P1 never suffers from this, but P2,P3,P4,... all have this problem.

**Comment by Buizz** [comment]
Can you give me log files of users whose data has disappeared?
Zip the log directory and give it to me.

**Comment by Chromowolf** [comment]
I've sent a bug report to scarchivereport@gmail.com. Please check it.

**Comment by Buizz** [comment]
Ok, I will check it

**Comment by Chromowolf** [comment]
I'm the map creator, I wanna somehow back up all user data once in a while, in case the previously stated bug happens again. How can I download all the user data from SCA official website? There's only a Batch Modification functionality, but I didn't find any "Batch download" option.

**Comment by Buizz** [comment]
Unfortunately not yet. There are plans.
And I analyzed the log you sent me.

I suspect that the code in the map is wrong.

![image](https://user-images.githubusercontent.com/19189816/130220282-5ca5c259-c803-4a89-a29e-2bcae67b3982.png)
![image](https://user-images.githubusercontent.com/19189816/130220297-e34b05ad-0979-481b-885f-b6c40d0b11fe.png)
![image](https://user-images.githubusercontent.com/19189816/130220307-43b2ce7d-2bb4-4fa9-bec5-d86aa3566e7d.png)
![image](https://user-images.githubusercontent.com/19189816/130220326-e43a073d-f221-40a4-8d3d-f1a77b303ba9.png)

**Comment by Chromowolf** [comment]
I use `SCAWrapper.scaSave(0, f_savecmp)` to save data.
During the game, when this function is called, SCA starts to save data.
If I quit before SCA finishes saving, then all the data becomes 0.
If I don't quit, then the data is saved as what it is.

I don't think this phenomenon can be caused by any eps code other than SCA.
I'll try to make a new map that can replicate this bug. BTW have you received similar bug report? I heard that the map Zombie Hunter also suffers from this.

**Comment by Buizz** [comment]
Currently, data initialization is occurring continuously.
We are not diagnosing the exact cause of it.

**Comment by Buizz** [comment]
As a result of checking a little more, it seems that data is lost if you exit in the middle of saving.
In addition to this, some suspicious points were found regarding the exit. First of all, we will try to improve it in the next version.

If this happens again, please keep reporting it to me.

**Comment by Chromowolf** [comment]
Thank you for the effort.
> some suspicious points were found regarding the exit

Could you elaborate more on this?

**Comment by Buizz** [comment]
The code related to the launcher will be fixed in the next patch.
To put it simply, I put ThreadSleep after the save command, and this seems to be the problem.

**Comment by Buizz** [comment]
Version was updated. Please check once.

**Comment by Chromowolf** [comment]
I tested using the same trick. Now the data won't be erased. Thanks!
