### ISSUE TITLE
SCA: How to set buffer size

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#61]
Is there a guide about what is / how to set the buffer size?
My map has over 20 SCA variables, but the buffer size is 300 (default). I don't know whether this is proper. What consequence can be caused by improper buffer size settings?

**Comment by Buizz** [comment]
Usually, one variable consumes 4 bytes. If it consumes the maximum, it consumes 8 bytes.
There's nothing wrong with having a large buffer, so you can just leave it as it is.

If the variable exceeds the size of the buffer, an overflow can occur and interrupt the trigger flow of the map.

**Comment by Chromowolf** [comment]
For example, I got 2 SCA variables, (1 variable and 1 array):
```js
const x = PVariable();  // 1 variable
const y = EUDArray(40);  // Array of length 5
```
How many variables is this equivalent to? 6, or 48?
How many bytes does it consume? 4*6=24 bytes, or 4*48=192 bytes?

**Comment by Chromowolf** [comment]
Is it possible to let EE3 automatically detect number of SCA variables and calculated the buffer size needed?

**Comment by Buizz** [comment]
To do that, we need a parser that can keep track of the length of the array.

**Comment by Chromowolf** [comment]
Maybe use regular expression? May not be hard to do :P

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
