### ISSUE TITLE
SCA: The "data lost" bug happened again

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#64]
I've sent the bug report to SCAreport via email. Please have a look when you are free. Thx!
![QQ图片20210903130109](https://user-images.githubusercontent.com/37732663/131952937-3e046a33-7e82-44a4-82a4-ffee7012282f.png)

BTW, do you have a develop team for SCA? Or you just develop SCA solely by your self?

**Comment by Buizz** [comment]
The program and overall logic are personal development.
The website has someone to help.

Let's take a look at the bug.

**Comment by Buizz** [comment]
There is no log for the date of September 2nd.

So further analysis is not possible.

Please check if you have confused your email account.

In the log, I played the first game on August 27th, and all data were processed normally.

**Comment by Chromowolf** [comment]
I've sent you the new Log file again. I checked his Log file and I don't know why there are only 6 files in the "default" folder. There are many records in the "save" and "load" folder. Is it possible to use these records to recover data?

**Comment by Chromowolf** [comment]
The data lost happed again
info of the player who lost all game data:starid: xiaoyang5821
email: 1355002079@qq.com
He lost all the data on a game around 2021-11-26, 15:30 (UTC+8)The files that may contain the information of this data lost are:Log\load\61C16C8A-3A9D-40C4-B642-E5E7DCE9E296.txtLog\save\F3CD14E3-C98C-4A80-B23E-83DF9B8D8E68.txtLog\save\D9A0B119-6672-476B-9726-02BDF0198CBA.txt
Plz see the attached file in the report email, thx!

**Comment by Buizz** [comment]
Close for issues cleanup.
If the problem is not solved yet, please post a new issue.
