### ISSUE TITLE
SCA Loading Fail 

### ISSUE THREAD

**Issue by gxz567** [Buizz/EUD-Editor-3#66]
Greetings!
      Sometimes SCA says "loaded successfully" `EPD(Db("\x07성공적으로 \x03데이터\x04를 불러왔습니다."))` ,however all SCA variebles are still "0".It says "success" but "fail" in fact.This BUG almost happened on someone whose network is bad.This BUG happens on the map "守卫神界" and the database is "GDW003".During this time,players said"my data is gone".If they exit the game without saving game and restart SCA several times,all data would be really successfully loaded.But once they SAVE with "0" data,all data really gone sadly. :( 
    By the way,once I exit the game when saving SCA and then restart the game,SCA said "success" but all data is "0".That is the BUG.
    Why does this BUG happen?

**Comment by Buizz** [comment]
If you bring the user's log, I will analyze it.

**Comment by gxz567** [comment]
Thx!Earlier logs missed.When I meet this again I will bring the log.
