### ISSUE TITLE
Some unit.dat changes (both valid and invalid) causes irregular wireframe changes

### ISSUE THREAD

**Issue by Arcyuryx** [Buizz/EUD-Editor-3#67]
**_EDIT IN REGARDS TO BELOW: the issue below is actually just, if you swap ANY wireframe, other wireframes get affected as well (and the wireframe that you WANTED to be swapped may not be swapped). I am keeping the below for posterity, so in case I'm somehow wrong._**

1. Copying UID 006 _terran siege tank turret (tank mode)_ onto a Zerg Ultralisk or Scantid (Desert) will cause the Photon Cannon wireframe to be changed to a Terran Nuclear Silo, the Terran Siege Tank (Sieged) wireframe to a Terran Marine's (might be the hero variant, don't know), as well as a couple of other wireframe swappages. 
2. Copying UID 005 _terran siege tank unit base (tank mode)_ onto Warbringer (Reaver) will cause the same above described wireframe swappings. If you manually modify the Warbringer entry and change the unit graphic to siege tank base, then subunit to UID 006 (its turret), without changing anything else, the wireframe changes will not occur. 

If I try and do `#1` in EUD Editor 2, the changes will compile successfully WITHOUT any wireframe changes.

**Comment by Arcyuryx** [comment]
Posting updated (I figured out it's probably just EE3 doesn't support wireframe changes yet)

**Comment by Buizz** [comment]
Have you ever run Starcraft in 64bit?

**Comment by Arcyuryx** [comment]
Yeah, it works in x32, but not 64. EE2 changes work in both x32 _and_ 64 though. I don't mind anywho :P

**Comment by Buizz** [comment]
Hmm... I'll check it.

**Comment by Arcyuryx** [comment]
I will double check myself too....

**Comment by Arcyuryx** [comment]
Forgot to update: the wireframe settings are in a different location in EE2 (it's not in datEdit). I messed it up - there's no bug with EE3. Thanks and sorry for the confusion.
