### ISSUE TITLE
SCA hard to connect

### ISSUE THREAD

**Issue by gxz567** [Buizz/EUD-Editor-3#68]
During these days many people in CN could hardly connect SCA.Is it the problem of service quality?

**Comment by Buizz** [comment]
There is currently a server issue.
How does it happen? Please show it with a picture.

**Comment by gxz567** [comment]
(I)On Oct 3 night,2 problems:
1.Program no responding at the game beginning.It work normally after a few seconds or minutes.
![SCA no response](https://user-images.githubusercontent.com/41184749/135799861-d12782c4-a14a-4589-9b95-68b89aef43e7.png)
2.Just keep loading but can't download data.It completed downloading after a few minutes.
(II)On Oct 4 11a.m. :
Program says `구버전 SCA로 빌드된 맵입니다!`
(III)On Oct4 13a.m. :
The same situation as (I).

The log is here:
[SCALog 2021.10.04-13.34.54.txt](https://github.com/Buizz/EUD-Editor-3/files/7275739/SCALog.2021.10.04-13.34.54.txt)

**Comment by Buizz** [comment]
**구버전 SCA로 빌드된 맵입니다!** is resolved by building with the latest version of EUD editor.
We are working on a fix for the jagged connection issue.

**Comment by gxz567** [comment]
Playing the same map,SCA no responding at 9a.m.,"구버전 SCA로 빌드된 맵입니다! " at 11a.m.,no responding again at 13a.m. Interesting.xD
Thx for debug!
