### ISSUE TITLE
Latest EE3 not compatible with current SCA

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#79]
I compiled my map using the latest version of EE3(0.12.9.0), and there is something wrong with SCA:

![QQ图片20211115012351](https://user-images.githubusercontent.com/37732663/141691475-34e7f04a-a89b-4bab-a73e-dc58925a2a20.png)

Everything is ok if I compile with the previous version of EE3 (0.12.8.1)

**Comment by Buizz** [comment]
The version does not match with version 0.0.0.5 because we do not proceed with the current SCA launcher follow-up patch. For SCA purposes, use the EUD editor as an older version.

**Comment by Chromowolf** [comment]
thx for the reply. Looking forward to the update of SCA
