### ISSUE TITLE
New SCA Setting would create a new database for the same map

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#80]
![image](https://user-images.githubusercontent.com/37732663/143731087-cfc8663e-ee8f-4c40-a312-bce4e9ef86eb.png)

I opened a project of my old map, entered my SCA email, and recompiled the map, then I got a new map code for my old map, hence a brand new database.
![image](https://user-images.githubusercontent.com/37732663/143731131-642e2f2b-5477-47b8-a86c-7f1184f3ede1.png)

By checking the "(Old) Use battle tag" box, the map code can remain to be the old one.

How is the mapcode generated? By some hash function using account email and password as input?

**Comment by Buizz** [comment]
it is created through the value entered in the email and ID Number fields. Previously, battle tags were used, but new users can no longer sign in with battle tags.
