### ISSUE TITLE
[SCA] Some players keep failing to upload data since SCA0.0.0.7

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#81]
There are many players in China have been reporting to me that SCA cannot upload data.
When `sca.upload(...)` is called during the game, their SCA becomes the "uploading" status for a long time and cannot upload data (seems no response):
![QQ图片20211207192436](https://user-images.githubusercontent.com/37732663/145020973-4172ad12-93a8-461e-9f0d-91107529ebc6.png)

FYI: My map has many SCAVariables, and a large buffer size (1000)
I myself could successfully upload/download data. But some other players can't (so it's not my code's problem). Also, the players who can't upload data in my map could upload data in another test map (so it's not anti-virus problem).
This issue happens since 2021-11-30.

**Comment by Buizz** [comment]
It is currently being resolved.
An error where too long data is truncated when sending data packets will be resolved in the near future.

**Comment by Buizz** [comment]
Problem solved, on 0.0.0.72
