### ISSUE TITLE
[SCA] Feature request: Get Unix Timestamp

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#82]
Currently, by calling the function `sca.LoadTime()`, SCA will load `Year`, `Month`, `Day`, `Hour`, `Min`, `Week`. Could you plz make it also load the current Unix timestamp?
Unix timestamp is easy to store and easy to be compared, making the time management more convenient.
Note that 0x6D0F38 is only the UNIX time of the local time of the game's host's computer, which could be changed by the host. So 0x6D0F38 is not reliable.
Plz consider this. Thx

**Comment by armoha** [comment]
Related place:
https://github.com/Buizz/EUD-Editor-3/blob/4fda5101d10d67229034e7e471e2abecabe93267/EUD%20Editor%203/Data/TriggerEditor/SCATool.eps#L138-L152

**Comment by armoha** [comment]
Unix timestamp is not only way to store datetime. (See [Are unix timestamps the best way to store timestamps?](https://stackoverflow.com/questions/178704/are-unix-timestamps-the-best-way-to-store-timestamps/178818))
It only stores 68 years range and starts from `January 1st, 1970 at UTC`; certainly it doesn't work well with birth date :D
