### ISSUE TITLE
[TextEditor] Crash when put `\x` in middle of text

### ISSUE THREAD

**Issue by armoha** [Buizz/EUD-Editor-3#84]
# Crash example
If you put `\x` in front of `Deaths` to write `\x1EDeaths` you got crash
![image](https://user-images.githubusercontent.com/16814706/148654014-1b17c6d8-ae06-4e10-a154-7f39a74be947.png)

# Left side bar text issue
~~W~~x01 \~ ~~W~~x1F all needs to change to  `\x01 ~ \x1F`

`\` looks ~~W~~ on Korean Windows,
~~Y~~ on Japanese Windows
`\` on US and European Windows
See [Backslash: Confusion with other characters](https://en.wikipedia.org/wiki/Backslash#Confusion_with_%C2%A5_and_other_characters)

> In the Japanese encodings ISO 646-JP (a 7-bit code based on ASCII), JIS X 0201 (an 8-bit code), and Shift JIS (a multi-byte encoding which is 8-bit for ASCII), the code point 0x5C that would be used for backslash in ASCII is instead rendered as a yen sign ¥. Due to extensive use of the 005C code point to represent the yen sign, even today some fonts such as MS Mincho render the backslash character as a ¥, so the characters at Unicode code points 00A5 (¥) and 005C (\) both render as ¥ when these fonts are selected. Computer programs still treat 005C as a backslash in these environments but display it as a yen sign, causing confusion, especially in MS-DOS filenames.[27]
> 
> Several other ISO 646 versions also replace backslash with other characters, including ₩ (Korean), Ö (German, Swedish), Ø (Danish, Norwegian), ç (French) and Ñ (Spanish), leading to similar problems, though with less lasting impact compared to the yen sign.

**Comment by Buizz** [comment]
I've fixed all of those issues.
