### ISSUE TITLE
Classic trigger comment text not displayed.

### ISSUE THREAD

**Issue by BeefaloKing** [Buizz/EUD-Editor-3#97]
Providing a comment makes the trigger (highlighted) appear blank in the list and you must open the edit dialogue to see the comment.

![image](https://user-images.githubusercontent.com/9630438/158498615-453aa8f9-a826-486e-adf7-5f75ce2c13ec.png)

**Comment by Buizz** [comment]
I will fix that in the next version.

**Comment by Buizz** [comment]
Complete in 0.13.0.4
